import io
from datetime import datetime, timezone
from typing import Any, Dict, Optional
from PIL import Image

from app.ai.base import CropHealthModel, CropHealthPrediction
from app.core.logging import logger


class DemoCropHealthModel(CropHealthModel):
    """
    Development Prototype Model for Multi-Modal Crop Health & Stress Inference.
    
    IMPORTANT SYSTEM NOTICE:
    - Status: DEMO / PROTOTYPE
    - Scientific Disclaimer: Non-diagnostic statistical model used for architecture verification.
    - Swappability: Conforms exactly to the CropHealthModel interface contract.
    """

    def __init__(self):
        self._name = "Kisan Sathi-Vision-DemoPrototype"
        self._version = "v0.1.0-prototype"

    @property
    def model_name(self) -> str:
        return self._name

    @property
    def model_version(self) -> str:
        return self._version

    @property
    def is_prototype(self) -> bool:
        return True

    async def predict(
        self,
        rgb_image_bytes: bytes,
        multispectral_bytes: Optional[bytes] = None,
        thermal_bytes: Optional[bytes] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> CropHealthPrediction:
        """
        Executes bounded statistical heuristic analysis on image pixel distribution.
        """
        # Default fallback metrics
        mean_r, mean_g, mean_b = 100.0, 150.0, 80.0
        width, height = 1920, 1080

        try:
            with Image.open(io.BytesIO(rgb_image_bytes)) as img:
                width, height = img.size
                # Downsample for fast raster statistic calculation
                small_img = img.convert("RGB").resize((128, 128))
                pixels = list(small_img.getdata())
                n_pixels = len(pixels)

                if n_pixels > 0:
                    sum_r = sum(p[0] for p in pixels)
                    sum_g = sum(p[1] for p in pixels)
                    sum_b = sum(p[2] for p in pixels)
                    mean_r = sum_r / n_pixels
                    mean_g = sum_g / n_pixels
                    mean_b = sum_b / n_pixels
        except Exception as err:
            logger.warning(f"Demo image decode exception ({err}). Using baseline telemetry.")

        # Compute Normalized Excess Green Index (2G - R - B)
        total_intensity = max(1.0, mean_r + mean_g + mean_b)
        norm_g = mean_g / total_intensity
        norm_r = mean_r / total_intensity
        norm_b = mean_b / total_intensity

        exg = (2.0 * norm_g) - norm_r - norm_b  # Typically ranges -1.0 to 1.0

        # Bound Health Score [0.0 - 1.0]
        # Higher green fraction indicates healthy chlorophyll canopy
        raw_health = 0.5 + (exg * 1.2)
        health_score = round(max(0.1, min(0.98, raw_health)), 3)

        # Vegetation Stress Score (inverse of vitality with color imbalance factor)
        vegetation_stress_score = round(max(0.02, min(0.95, 1.0 - health_score + (norm_r * 0.1))), 3)

        # Anomaly Score (variance indicator)
        anomaly_score = round(max(0.05, min(0.90, abs(norm_g - 0.45) * 1.5)), 3)

        # Pathology & Pest Likelihoods
        # Elevated chlorosis/necrosis (red/yellow bias) correlates with disease probability
        disease_prob = round(max(0.02, min(0.85, (norm_r * 1.2) + (anomaly_score * 0.3))), 3)
        pest_prob = round(max(0.01, min(0.75, (anomaly_score * 0.6) + (vegetation_stress_score * 0.2))), 3)

        # Model Epistemic Confidence
        confidence = 0.82 if not multispectral_bytes else 0.94

        prediction_meta = {
            "prototype_label": "DEMO / PROTOTYPE",
            "scientific_disclaimer": (
                "DEMO / PROTOTYPE: This inference was generated by a statistical development prototype "
                "for software scaffolding and pipeline verification. It does NOT claim certified agronomic disease diagnosis."
            ),
            "input_resolution": f"{width}x{height}",
            "bands_analyzed": ["RGB"] + (["Multispectral_NIR"] if multispectral_bytes else []) + (["Thermal_LWIR"] if thermal_bytes else []),
            "estimated_exg_index": round(exg, 4),
            "mean_rgb_ratios": {
                "red_ratio": round(norm_r, 3),
                "green_ratio": round(norm_g, 3),
                "blue_ratio": round(norm_b, 3),
            },
            "context_metadata": metadata or {},
        }

        return CropHealthPrediction(
            health_score=health_score,
            vegetation_stress_score=vegetation_stress_score,
            anomaly_score=anomaly_score,
            disease_probability=disease_prob,
            pest_probability=pest_prob,
            confidence=confidence,
            model_name=self.model_name,
            model_version=self.model_version,
            inference_timestamp=datetime.now(timezone.utc),
            prediction_metadata=prediction_meta,
        )


demo_crop_health_model = DemoCropHealthModel()
