import React, { useEffect, useState } from 'react';
import { BrainCircuit, AlertTriangle, CheckCircle2, TrendingDown, ChevronLeft, ShieldCheck, History } from 'lucide-react';
import { useDiagnosisWizard } from './DiagnosisWizardContext';
import { diagnosisService, SymptomAnalysisPayload } from '@/services/diagnosisService';

interface Props {
  onPrev: () => void;
  onReset: () => void;
}

export const Step7AIAnalysis: React.FC<Props> = ({ onPrev, onReset }) => {
  const {
    selectedFarmId, selectedZoneId, selectedCrop, growthStage,
    selectedPlantParts, selectedSymptoms, severity, distribution,
    symptomDuration, farmerNotes, uploadedImages,
    analysisResult, setAnalysisResult
  } = useDiagnosisWizard();

  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!analysisResult) {
      runAnalysis();
    }
  }, []);

  const runAnalysis = async () => {
    setIsAnalyzing(true);
    setError(null);

    const payload: SymptomAnalysisPayload = {
      farm_id: selectedFarmId,
      zone_id: selectedZoneId,
      crop_type: selectedCrop,
      growth_stage: growthStage,
      plant_parts: selectedPlantParts,
      symptoms: selectedSymptoms,
      severity,
      distribution,
      symptom_start_date: symptomDuration,
      farmer_notes: farmerNotes,
      has_images: uploadedImages.length > 0,
      image_urls: uploadedImages.map((img) => img.url),
    };

    try {
      const result = await diagnosisService.analyzeSymptoms(payload);
      setAnalysisResult(result);
    } catch (err: any) {
      setError(err.message || 'Failed to complete AI analysis');
    } finally {
      setIsAnalyzing(false);
    }
  };

  if (isAnalyzing) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] text-center space-y-4 animate-in fade-in duration-500">
        <BrainCircuit className="w-16 h-16 text-emerald-600 animate-pulse" />
        <h3 className="text-xl font-bold text-slate-800">Processing Diagnostic Pipeline...</h3>
        <p className="text-slate-500 max-w-md">
          Synthesizing symptoms, spatial context, and visual evidence through our multi-vector symptom reasoner.
        </p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] text-center space-y-4">
        <AlertTriangle className="w-16 h-16 text-red-500" />
        <h3 className="text-xl font-bold text-slate-800">Analysis Failed</h3>
        <p className="text-red-600 max-w-md">{error}</p>
        <button
          onClick={runAnalysis}
          className="mt-4 px-6 py-2 bg-slate-800 text-white rounded-lg hover:bg-slate-700"
        >
          Retry Analysis
        </button>
      </div>
    );
  }

  if (!analysisResult) return null;

  return (
    <div className="space-y-8 animate-in fade-in duration-700">
      <div className="flex items-center justify-between border-b pb-4">
        <div>
          <h2 className="text-xl font-semibold text-slate-800 flex items-center gap-2">
            <BrainCircuit className="text-emerald-600" />
            Diagnostic Results
          </h2>
          <p className="text-sm text-slate-500 mt-1">
            Generated by {analysisResult.model_name} ({analysisResult.model_version})
          </p>
        </div>
        
        {analysisResult.status === 'AI_SUSPECTED' ? (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-100 text-blue-700 font-medium text-sm border border-blue-200">
            <ShieldCheck className="w-4 h-4" />
            AI Suspected
          </span>
        ) : (
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-100 text-amber-700 font-medium text-sm border border-amber-200">
            <AlertTriangle className="w-4 h-4" />
            {analysisResult.status}
          </span>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Primary Diagnosis */}
        <div className={`p-6 rounded-xl border ${
          analysisResult.disease_confidence > 0.7 
            ? 'bg-emerald-50 border-emerald-200'
            : 'bg-amber-50 border-amber-200'
        }`}>
          <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-2">Primary Condition</h3>
          <div className="text-2xl font-bold text-slate-800">{analysisResult.primary_condition}</div>
          
          <div className="mt-4 flex items-center gap-4">
            <div>
              <div className="text-xs text-slate-500 mb-1">Disease Confidence</div>
              <div className="flex items-center gap-2">
                <div className="w-24 h-2 bg-slate-200 rounded-full overflow-hidden">
                  <div 
                    className={`h-full ${analysisResult.disease_confidence > 0.7 ? 'bg-emerald-500' : 'bg-amber-500'}`}
                    style={{ width: `${analysisResult.disease_confidence * 100}%` }}
                  />
                </div>
                <span className="font-bold text-sm text-slate-700">
                  {Math.round(analysisResult.disease_confidence * 100)}%
                </span>
              </div>
            </div>

            <div>
              <div className="text-xs text-slate-500 mb-1">Crop Confidence</div>
              <div className="flex items-center gap-2">
                <div className="w-24 h-2 bg-slate-200 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-blue-500"
                    style={{ width: `${analysisResult.crop_confidence * 100}%` }}
                  />
                </div>
                <span className="font-bold text-sm text-slate-700">
                  {Math.round(analysisResult.crop_confidence * 100)}%
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Alternative Candidates */}
        <div className="bg-slate-50 border border-slate-200 rounded-xl p-6">
          <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">Differential Diagnosis</h3>
          <div className="space-y-4">
            {analysisResult.possible_conditions.map((cond, idx) => (
              <div key={idx} className="flex items-center justify-between">
                <div>
                  <div className="font-medium text-slate-800 text-sm">{cond.condition_name}</div>
                  <div className="text-xs text-slate-500">{cond.pathogen_type}</div>
                </div>
                <div className="text-sm font-bold text-slate-600 bg-white px-2 py-1 rounded border shadow-sm">
                  {Math.round(cond.probability * 100)}%
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
        <div className="bg-slate-50 px-6 py-4 border-b border-slate-200">
          <h3 className="font-bold text-slate-800">Action Plan & Recommendations</h3>
        </div>
        <div className="p-6">
          <ul className="space-y-4">
            {analysisResult.recommendations.map((rec, idx) => (
              <li key={idx} className="flex gap-4">
                <div className={`mt-0.5 w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 ${
                  rec.action_type === 'IMMEDIATE' ? 'bg-red-100 text-red-600' :
                  rec.action_type === 'IPM' ? 'bg-emerald-100 text-emerald-600' :
                  'bg-blue-100 text-blue-600'
                }`}>
                  <CheckCircle2 className="w-4 h-4" />
                </div>
                <div>
                  <div className="font-semibold text-slate-800">{rec.title}</div>
                  <div className="text-sm text-slate-600 mt-1">{rec.description}</div>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="flex justify-between pt-6 border-t mt-8">
        <button
          onClick={onPrev}
          className="flex items-center gap-2 bg-slate-100 hover:bg-slate-200 text-slate-700 px-6 py-2 rounded-lg font-medium transition-colors"
        >
          <ChevronLeft className="w-4 h-4" />
          Back
        </button>
        <button
          onClick={onReset}
          className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-6 py-2 rounded-lg font-medium transition-colors"
        >
          Start New Case
        </button>
      </div>
    </div>
  );
};
