import React from 'react';
import {
  Sparkles,
  AlertTriangle,
  Activity,
  Droplets,
  Bug,
  ShieldAlert,
  Info,
  Database,
} from 'lucide-react';
import { CropHealthAnalysisResponse, DroneImage } from '@/types';

interface CropHealthAnalysisModalProps {
  image: DroneImage;
  analysis: CropHealthAnalysisResponse | null;
  isLoading: boolean;
  onClose: () => void;
}

export const CropHealthAnalysisModal: React.FC<CropHealthAnalysisModalProps> = ({
  image,
  analysis,
  isLoading,
  onClose,
}) => {
  return (
    <div className="fixed inset-0 z-50 bg-slate-950/85 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="max-w-2xl w-full p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-2xl space-y-5 max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-emerald-400 animate-pulse" />
            <div>
              <h3 className="font-bold text-slate-100 text-base">
                Crop Health AI Vision Inference
              </h3>
              <p className="text-xs text-slate-400">
                Frame: <span className="font-mono text-slate-200">{image.filename}</span> ({image.sensor_type})
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="text-slate-500 hover:text-slate-300 transition text-sm"
          >
            ✕
          </button>
        </div>

        {/* Prototype Scientific Disclaimer Alert */}
        <div className="p-3.5 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-300 text-xs flex items-start gap-2.5">
          <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5 text-amber-400" />
          <div className="space-y-0.5">
            <span className="font-bold uppercase tracking-wider text-[11px] block text-amber-400">
              DEMO / PROTOTYPE — Non-Diagnostic Model
            </span>
            <p className="text-slate-300 text-[11px] leading-relaxed">
              This inference was generated by the modular development prototype model (
              <span className="font-mono text-amber-300">{analysis?.model_name || 'DemoCropHealthModel'}</span>) for system scaffolding and pipeline verification. It does NOT constitute a certified agronomic diagnosis.
            </p>
          </div>
        </div>

        {isLoading ? (
          <div className="p-12 text-center text-slate-400 space-y-3">
            <div className="w-8 h-8 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin mx-auto" />
            <p className="text-xs">Executing multi-spectral raster inference...</p>
          </div>
        ) : analysis ? (
          <div className="space-y-5">
            {/* Primary Scores Grid */}
            <div className="grid grid-cols-3 gap-3">
              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-center space-y-1">
                <span className="text-[11px] text-slate-400 block font-medium flex items-center justify-center gap-1">
                  <Activity className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Health Vitality</span>
                </span>
                <p className="text-2xl font-black font-mono text-emerald-400">
                  {(analysis.health_score * 100).toFixed(1)}%
                </p>
                <span className="text-[10px] text-slate-500 block">Chlorophyll Index</span>
              </div>

              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-center space-y-1">
                <span className="text-[11px] text-slate-400 block font-medium flex items-center justify-center gap-1">
                  <Droplets className="w-3.5 h-3.5 text-blue-400" />
                  <span>Vegetation Stress</span>
                </span>
                <p className="text-2xl font-black font-mono text-blue-400">
                  {(analysis.vegetation_stress_score * 100).toFixed(1)}%
                </p>
                <span className="text-[10px] text-slate-500 block">Stomatal Water Deficit</span>
              </div>

              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-center space-y-1">
                <span className="text-[11px] text-slate-400 block font-medium flex items-center justify-center gap-1">
                  <ShieldAlert className="w-3.5 h-3.5 text-orange-400" />
                  <span>Canopy Anomaly</span>
                </span>
                <p className="text-2xl font-black font-mono text-orange-400">
                  {(analysis.anomaly_score * 100).toFixed(1)}%
                </p>
                <span className="text-[10px] text-slate-500 block">Spatial Deviation</span>
              </div>
            </div>

            {/* Pathology & Pest Risk Indicators */}
            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-3">
              <h4 className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                <Info className="w-3.5 h-3.5 text-blue-400" />
                <span>Pathology & Pest Risk Likelihoods</span>
              </h4>

              <div className="space-y-2 text-xs">
                <div>
                  <div className="flex justify-between text-slate-400 mb-1">
                    <span className="flex items-center gap-1">
                      <ShieldAlert className="w-3 h-3 text-rose-400" />
                      <span>Foliar Disease Likelihood:</span>
                    </span>
                    <span className="font-mono font-bold text-slate-200">
                      {(analysis.disease_probability * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="w-full bg-slate-800 h-1.5 rounded-full overflow-hidden">
                    <div
                      className="bg-rose-500 h-full rounded-full transition-all"
                      style={{ width: `${analysis.disease_probability * 100}%` }}
                    />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-slate-400 mb-1">
                    <span className="flex items-center gap-1">
                      <Bug className="w-3 h-3 text-amber-400" />
                      <span>Pest Defoliation Likelihood:</span>
                    </span>
                    <span className="font-mono font-bold text-slate-200">
                      {(analysis.pest_probability * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="w-full bg-slate-800 h-1.5 rounded-full overflow-hidden">
                    <div
                      className="bg-amber-500 h-full rounded-full transition-all"
                      style={{ width: `${analysis.pest_probability * 100}%` }}
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Linked PostGIS Observations & Model Metadata */}
            <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800 space-y-2 text-xs">
              <div className="flex items-center justify-between text-slate-400 border-b border-slate-800/80 pb-2">
                <span className="flex items-center gap-1.5">
                  <Database className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Persisted Domain Observations:</span>
                </span>
                <span className="font-mono text-[10px] text-emerald-400">PostGIS SRID 4326</span>
              </div>

              <div className="grid grid-cols-2 gap-2 text-[11px] font-mono">
                <div>
                  <span className="text-slate-500 block">Health Observation:</span>
                  <span className="text-slate-300 truncate block">
                    {analysis.health_observation_id || 'N/A'}
                  </span>
                </div>
                <div>
                  <span className="text-slate-500 block">Disease Observation:</span>
                  <span className="text-slate-300 truncate block">
                    {analysis.disease_observation_id || 'None (Below threshold)'}
                  </span>
                </div>
                <div>
                  <span className="text-slate-500 block">Model Tag:</span>
                  <span className="text-slate-300">{analysis.model_name} ({analysis.model_version})</span>
                </div>
                <div>
                  <span className="text-slate-500 block">Confidence:</span>
                  <span className="text-emerald-400 font-bold">{(analysis.confidence * 100).toFixed(0)}%</span>
                </div>
              </div>
            </div>
          </div>
        ) : null}

        {/* Footer */}
        <div className="flex justify-end pt-3 border-t border-slate-800">
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition"
          >
            Dismiss Analysis
          </button>
        </div>
      </div>
    </div>
  );
};
